routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('report/{type}/{period}', 'ReportController@show')->name('report.show');
    Route::get('report', 'ReportController@index')->name('report.index');

    Route::get('save', 'AmountController@store')->name('save');
    Route::get('users', 'UserController@index')->name('user.index');

    Route::resource('transaction', 'TransactionController');

    Route::get('home', 'TransactionController@index')->name('home');
});

app/Models/Amount.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Amount extends Model
{
    protected $fillable = ['transaction_id', 'amount'];

    public function transaction()
    {
        return $this->belongsTo(Transaction::class);
    }

}

app/Models/Role.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'id'
    ];

    public $timestamps = false;

    public function users()
    {
        return $this->hasMany(User::class);
    }
}

app/Models/Transaction.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Transaction
 *
 * @package App\Models
 */
class Transaction extends Model
{
    /**
     * @var array
     */
    protected $fillable = ['user_id', 'failed'];

    /**
     * Return a builder or a collection with the amount of the transaction
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function amount()
    {
        return $this->hasOne(Amount::class);
    }

    /**
     * Return a builder or a collection with the user that owns the transaction
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use App\Models\Role;
use App\Models\Transaction;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }

    public function isAdmin()
    {
        return $this->role->name == 'admin';
    }

    public function hasPendingTransaction()
    {
        $transactions = $this->transactions()
            ->whereNull('failed')
            ->whereDoesntHave('amount')
            ->count();

        return $transactions > 0;
    }
}

app/Http/Controllers/AmountController.php
<?php

namespace App\Http\Controllers;

use App\Models\Amount;
use App\Models\Transaction;
use Illuminate\Http\Request;
use Mockery\Exception\NoMatchingExpectationException;

class AmountController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $transaction = Transaction::findOrfail($request->transaction_id);

        if ($transaction->user_id != $request->user_id) {
            throw new NoMatchingExpectationException('User does not match transaction user');
        }
        $amount = Amount::create($request->except('user_id'));

        $amount->transaction->update(['failed' => 0]);

        return redirect('/home');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Http\Helpers\DateTimeHelper;
use App\Http\Helpers\ReportsHelper;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Response;

/**
 * Class ReportController
 *
 * @package App\Http\Controllers
 */
class ReportController extends Controller
{
    /**
     * Show the report page
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        if (!Gate::allows('report-index')) {
            abort(403);
        }
        return view('reports');

    }

    /**
     * Return the report data
     *
     * @param $type
     * @param $period
     * @return \Illuminate\Http\JsonResponse
     */
    public function show($type, $period, DateTimeHelper $helper)
    {
        if (!Gate::allows('report-index')) {
            abort(403);
        }
        /* TODO: change to strategy pattern */
        $reportHelper = new ReportsHelper();
        if ($type == 'top5') {
            $report = $reportHelper->getTopUsersByTransactionCount(...$helper->generateDates($period));
        } else {
            $report = $reportHelper->getAmountPerDay(...$helper->generateDates($period));
        }

        return Response::json($report);
    }
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Transaction;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

/**
 * Class TransactionController
 *
 * @package App\Http\Controllers
 */
class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Gate::allows('transaction-index')) {
            $transactions = Transaction::all();
            return view('admin.transaction')->withTransactions($transactions);
        }
        return redirect(route('transaction.show', auth()->user()->id));
    }

    /**
     * @param int $userId
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(int $userId)
    {
        $user = User::findOrfail($userId);

        if (auth()->user()->hasPendingTransaction() && auth()->user()->id == $userId) {
            return view('amount');
        }

        $transactions = $user->transactions;

        return view('transaction')->withTransactions($transactions);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->_token) {
            if (Transaction::create(['user_id' => auth()->user()->id])) {
                return view('amount');
            }
        }
        return view('transaction');

    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Support\Facades\Gate;

/**
 * Class UserController
 *
 * @package App\Http\Controllers
 */
class UserController extends Controller
{

    /**
     * Display a listing of all the users
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        if (!Gate::allows('user-index')) {
            abort(403);
        }
        $users = User::whereHas('role', function ($query){
            $query->where('name', 'user');
        })->get();
        return view('admin.users')->withUsers($users);
    }
}

resources/views/admin/transaction.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Transaction') }}</div>

                    <ul>
                        @foreach($transactions as $transaction)
                            <p> Transaction from {{$transaction->created_at}}</p>
                            <li>
                                Status: {{$transaction->failed == 0 ? 'paid' : ($transaction->failed == null ? 'pending' : 'failed') }}</li>
                            <li> User: <a href="{{route('transaction.show', $transaction->user->id)}}">
                                    {{$transaction->user->name}}
                                </a>
                            </li>
                            <li> Amount: {{$transaction->amount->amount ?? 'n/a'}}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('User list') }}</div>

                    <ul>
                        @foreach($users as $user)
                            <li> <a href="{{route('transaction.show', $user->id)}}">
                                    {{$user->name}} | {{$user->email}}
                                </a>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/amount.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Finish transaction') }}</div>

                    <div class="card-body">
                        <form method="get" action="{{ route('save') }}">
                            <div class="form-group row">
                                <label for="amount"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Amount') }}</label>

                                <div class="col-md-6">
                                    <input id="amount" type="number"
                                           class="form-control @error('amount') is-invalid @enderror" name="amount"
                                           value="{{ old('amount') }}" required autofocus>

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <input name="user_id" id="user_id" type="hidden" value="{{ auth()->user()->id }}">
                            <input name="transaction_id" id="transaction_id" type="hidden"
                                   value="{{ auth()->user()->transactions->last()->id }}">

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Finish') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Test') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Test') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        @if(auth()->user()->isAdmin())
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('user.index')}}"> Users </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('report.index')}}"> Reports </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('transaction.index')}}"> All Transactions </a>
                            </li>
                        @endif
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/reports.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="form-group">
                        <label for="sel1">Report type</label>
                        <select class="form-control" id="report">
                            <option value="amount">Amount</option>
                            <option value="top5">Top 5</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="sel1">Period</label>
                        <select class="form-control" id="period">
                            <option value="lastWeek">Last week</option>
                            <option value="lastMonth">Last month</option>
                            <option value="allTime">All time</option>
                        </select>
                    </div>
                    <button class="btn btn-primary" type="button" name="Show" onclick="load()">Load report</button>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <ul id="report-area">

                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection

<script>
  function load() {
    var report = document.getElementById("report");
    var reportType = report.options[report.selectedIndex].value;
    var period = document.getElementById("period");
    var reportPeriod = period.options[period.selectedIndex].value;

    getReport(reportType, reportPeriod);
  }

  function getReport(reportType, reportPeriod) {
    const xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function () {
      if (this.readyState == 4 && this.status == 200) {
        document.getElementById("report-area").innerHTML = "";
        let response = JSON.parse(this.responseText);
        response.forEach(addReportData);
      }
    };
    xhttp.open("GET", "/report/" + reportType + '/' + reportPeriod, true);
    xhttp.send();
  }

  function addReportData(item) {
    let html = "<li>" + JSON.stringify(item) + "</li>"
    document.getElementById("report-area").innerHTML += html;
  }
</script>

resources/views/transaction.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if(auth()->user()->id == $user->id)
                    <div class="card">
                        <div class="card-header">{{ __('Transaction') }}</div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('transaction.store') }}">
                                @csrf

                                <div class="form-group row mb-0">
                                    <div class="col-md-8 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                            {{ __('Begin transaction') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                @endif
                <div class="card">
                    <div class="card-header">{{ __('Transaction list') }}</div>
                    <div class="card-body">
                        <ul>
                            @foreach($transactions as $transaction)
                                <p> Transaction from {{$transaction->created_at}}</p>
                                <li>
                                    Status: {{$transaction->failed == 0 ? 'paid' : ($transaction->failed == null ? 'pending' : 'failed') }}</li>
                                <li> User: {{$transaction->user->name}}</li>
                                <li> Amount: {{$transaction->amount->amount ?? 'n/a'}}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection